#!/bin/bash

# Allowed choices are 5min, 10min, 1hour, 1day, 1week, 1month, 1year, never.

docker run -i \
	--rm \
	--name=sender \
	-e NODE_NO_WARNINGS=1 \
	-e NODE_TLS_REJECT_UNAUTHORIZED=0 \
	fabiop85/pbclinode:latest privatebin send \
		-e 10min \
		-u https://privatebin.adiprint.it
